name: RunChecks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get -y install python3-apt
        python -m pip install --upgrade pip
        pip install -r gateway/requirements.txt
        pip install -r python-sdk/sample-ptyhon-app/requirements.txt
    - name: Analysing python api with pylint
      run: |
        cd gateway
        find . -type f -name \*.py -print | egrep -v '(proto|silabs)'| xargs pylint -dC0103,E1101,E0401,E1136,W0703,R0801,R0902,R0903,R0913,R0912,R0914 > pylint.out
    - name: Attempting install
      run: |
        cd python-sdk
        pip install .
        echo 'import tiedie' | python

